// Package uowstore is a DERISK SPIKE (issue gastownhall/beads#4547, Route A).
//
// It implements a tiny slice of storage.DoltStorage over the unit-of-work
// stack (internal/storage/uow + internal/storage/domain), proving that the
// full "uowStore adapter" sketched in PROPOSAL-uowstore-adapter.md §2 is
// buildable: one adapter type presenting the old store interface, with each
// call becoming one short UOW transaction (exactly the proxied-server design).
//
// UNIMPLEMENTED METHODS RETURN A TYPED ERROR, NEVER PANIC. uowStore embeds the
// generated unsupportedDoltStorage shell (unsupported_gen.go): every method of
// the 144-method interface that this spike does not really override returns a
// *storage.ErrUnsupported naming the operation and this backend, wrapped with
// BD_SPIKE_UOWSTORE / issue #4547 context. That replaces the earlier nil-embed
// shortcut whose untouched methods nil-panicked (SPIKE-REPORT §6.4/§6.6). The
// shell is regenerated by `go generate ./...`; two compile-time assertions in
// the generated file break the build if DoltStorage or Transaction grows a
// method, forcing a regen instead of letting a silent stub answer for it. This
// type must NEVER be shipped as a general store.
package uowstore

//go:generate go run ./gen

import (
	"context"
	"database/sql"
	"errors"
	"fmt"

	"github.com/steveyegge/beads/internal/storage"
	"github.com/steveyegge/beads/internal/storage/domain"
	"github.com/steveyegge/beads/internal/storage/uow"
	"github.com/steveyegge/beads/internal/types"
)

// uowStore adapts a uow.UnitOfWorkProvider to the storage.DoltStorage
// interface. The embedded unsupportedDoltStorage shell supplies typed
// *storage.ErrUnsupported implementations for every method this spike does not
// override (see package doc); the real vertical slice is the methods below.
type uowStore struct {
	unsupportedDoltStorage // generated shell: unimplemented methods return typed ErrUnsupported, never panic

	provider uow.UnitOfWorkProvider
	actor    string // construction-time identity; unused in the spike slice (see New)
}

// New wraps a UnitOfWorkProvider as a spike storage.DoltStorage. actor is the
// construction-time audit identity. NOTE: it is currently UNUSED — every store
// method this spike overrides (CreateIssue, CloseIssue, …) carries its own actor
// argument, so nothing reads s.actor. It is retained deliberately: §4.0's
// Identity-on-the-seam rule means the full adapter will need a construction-time
// actor for the methods that lack one, and threading getActor() here documents
// that seam now. Drop it if the real adapter proves it is never needed.
func New(provider uow.UnitOfWorkProvider, actor string) storage.DoltStorage {
	return &uowStore{provider: provider, actor: actor}
}

var _ storage.DoltStorage = (*uowStore)(nil)

// ---- reads: open UOW, call use-case, Close (rollback). NEVER Commit("") ----

// GetIssue mirrors issueops.GetIssueInTx: probe the issues table, then the
// wisps table, and return storage.ErrNotFound (not sql.ErrNoRows) when neither
// has the row. The use-case's GetIssue only probes issues and surfaces a
// wrapped sql.ErrNoRows, so the adapter owns both the wisp fallback and the
// error-code translation the store contract requires.
func (s *uowStore) GetIssue(ctx context.Context, id string) (*types.Issue, error) {
	u, err := s.provider.NewUOW(ctx)
	if err != nil {
		return nil, err
	}
	defer u.Close(ctx)
	issue, err := getIssueInUOW(ctx, u, id)
	return issue, mapUowError(err)
}

// GetIssuesByIDs backs the molecule-ancestry resolution in the close path
// (findParentMolecules -> GetIssuesByIDs, cmd/bd/mol_current.go:456). DIRECT.
func (s *uowStore) GetIssuesByIDs(ctx context.Context, ids []string) ([]*types.Issue, error) {
	u, err := s.provider.NewUOW(ctx)
	if err != nil {
		return nil, err
	}
	defer u.Close(ctx)
	out, err := u.IssueUseCase().GetIssuesByIDs(ctx, ids)
	return out, mapUowError(err)
}

func (s *uowStore) SearchIssues(ctx context.Context, query string, filter types.IssueFilter) ([]*types.Issue, error) {
	u, err := s.provider.NewUOW(ctx)
	if err != nil {
		return nil, err
	}
	defer u.Close(ctx)

	page, err := u.IssueUseCase().SearchIssues(ctx, query, filter)
	if err != nil {
		return nil, mapUowError(err)
	}
	return page.Items, nil
}

func (s *uowStore) SearchIssuesWithCounts(ctx context.Context, query string, filter types.IssueFilter) ([]*types.IssueWithCounts, error) {
	u, err := s.provider.NewUOW(ctx)
	if err != nil {
		return nil, err
	}
	defer u.Close(ctx)

	page, err := u.IssueUseCase().SearchIssuesWithCounts(ctx, query, filter)
	if err != nil {
		return nil, mapUowError(err)
	}
	return page.Items, nil
}

func (s *uowStore) GetReadyWork(ctx context.Context, filter types.WorkFilter) ([]*types.Issue, error) {
	u, err := s.provider.NewUOW(ctx)
	if err != nil {
		return nil, err
	}
	defer u.Close(ctx)

	page, err := u.IssueUseCase().GetReadyWork(ctx, filter)
	if err != nil {
		return nil, mapUowError(err)
	}
	return page.Items, nil
}

func (s *uowStore) GetReadyWorkWithCounts(ctx context.Context, filter types.WorkFilter) ([]*types.IssueWithCounts, error) {
	u, err := s.provider.NewUOW(ctx)
	if err != nil {
		return nil, err
	}
	defer u.Close(ctx)

	page, err := u.IssueUseCase().GetReadyWorkWithCounts(ctx, filter)
	if err != nil {
		return nil, mapUowError(err)
	}
	return page.Items, nil
}

// ---- writes: one short tx via uow.RunInTx with an outcome-derived message ----

// CreateIssue mirrors EmbeddedDoltStore.CreateIssue: infra types route to the
// wisps table, and the caller's *types.Issue is mutated in place with the
// minted ID (the use-case operates on the same pointer via CreateIssueParams).
//
// Label mapping is load-bearing: the embedded store persists issue.Labels (via
// issueops.PersistLabels, which reads the *types.Issue), but the domain create
// use-case reads only params.Labels — so the adapter must copy issue.Labels
// across, or bd create silently drops every label on this path (#4547 red-team).
// issue.Comments is NOT mapped: the create use-case has no comment path, and the
// store-path bd create never populates Comments (comments arrive via bd comment
// add). A full adapter that must round-trip imported comments needs a
// comment-write gap unit — see SPIKE-REPORT §3.
func (s *uowStore) CreateIssue(ctx context.Context, issue *types.Issue, actor string) error {
	if issue == nil {
		return fmt.Errorf("issue must not be nil")
	}
	if err := s.prepareForCreate(ctx, issue); err != nil {
		return err
	}

	params := domain.CreateIssueParams{Issue: issue, Labels: issue.Labels}
	return uow.RunInTxMsg(ctx, s.provider, func(u uow.UnitOfWork) (string, error) {
		var (
			res domain.CreateIssueResult
			err error
		)
		// Route ephemeral AND no-history beads to the wisps table, mirroring
		// EmbeddedDoltStore.CreateIssue's `useWispsTable := Ephemeral || NoHistory
		// || infra`. no_history beads live in wisps with ephemeral=0, so
		// `list --all` (SkipWisps) hides them while `ready` (issues∪wisps union)
		// still surfaces them — the tier set-algebra embedded produces (#4547 F-2).
		// NoHistory does NOT set issue.Ephemeral, so the create JSON is unchanged.
		if issue.Ephemeral || issue.NoHistory {
			res, err = u.IssueUseCase().CreateWisp(ctx, params, actor)
		} else {
			res, err = u.IssueUseCase().CreateIssue(ctx, params, actor)
		}
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("bd: create %s", res.Issue.ID), nil
	})
}

// CloseIssue mirrors EmbeddedDoltStore.CloseIssue: the raw close op only
// (command-level validation — epic children, gate satisfaction, blocker checks
// — lives above the store and is out of scope here). Probes issue-or-wisp so
// the right table is closed, exactly as the proxied close command does.
func (s *uowStore) CloseIssue(ctx context.Context, id string, reason string, actor string, session string) error {
	return mapUowError(uow.RunInTxMsg(ctx, s.provider, func(u uow.UnitOfWork) (string, error) {
		if err := closeIssueInUOW(ctx, u, id, reason, actor, session); err != nil {
			return "", err
		}
		return fmt.Sprintf("bd: close %s", id), nil
	}))
}

// ---- show-detail reads (labels / deps-with-metadata / counts) ----
//
// `bd show --json` (default output) fans out from GetIssue into these five
// reads before rendering (cmd/bd/show.go:149-158), so the "get" leg of the
// round-trip needs them. GetLabels and the counts are DIRECT; the
// *WithMetadata pair is the doc's §4.2 COMPOSE (ListWithIssueMetadata with a
// direction). NOTE: the store's counts sum the regular + wisp dependency
// tables (embeddeddolt/counts.go); this spike counts only the regular table
// via the use-case, which is correct for regular issues but is the documented
// wisp-union gap for a full adapter.

func (s *uowStore) GetLabels(ctx context.Context, issueID string) ([]string, error) {
	u, err := s.provider.NewUOW(ctx)
	if err != nil {
		return nil, err
	}
	defer u.Close(ctx)
	out, err := u.LabelUseCase().GetLabels(ctx, issueID)
	return out, mapUowError(err)
}

func (s *uowStore) GetDependenciesWithMetadata(ctx context.Context, issueID string) ([]*types.IssueWithDependencyMetadata, error) {
	u, err := s.provider.NewUOW(ctx)
	if err != nil {
		return nil, err
	}
	defer u.Close(ctx)
	out, err := u.DependencyUseCase().ListWithIssueMetadata(ctx, issueID, domain.DepListFilter{Direction: domain.DepDirectionOut})
	return out, mapUowError(err)
}

func (s *uowStore) GetDependentsWithMetadata(ctx context.Context, issueID string) ([]*types.IssueWithDependencyMetadata, error) {
	u, err := s.provider.NewUOW(ctx)
	if err != nil {
		return nil, err
	}
	defer u.Close(ctx)
	out, err := u.DependencyUseCase().ListWithIssueMetadata(ctx, issueID, domain.DepListFilter{Direction: domain.DepDirectionIn})
	return out, mapUowError(err)
}

func (s *uowStore) CountDependencies(ctx context.Context, issueID string) (int64, error) {
	u, err := s.provider.NewUOW(ctx)
	if err != nil {
		return 0, err
	}
	defer u.Close(ctx)
	n, err := u.DependencyUseCase().CountByIssueID(ctx, issueID, domain.DepListFilter{Direction: domain.DepDirectionOut})
	return n, mapUowError(err)
}

func (s *uowStore) CountDependents(ctx context.Context, issueID string) (int64, error) {
	u, err := s.provider.NewUOW(ctx)
	if err != nil {
		return 0, err
	}
	defer u.Close(ctx)
	n, err := u.DependencyUseCase().CountByIssueID(ctx, issueID, domain.DepListFilter{Direction: domain.DepDirectionIn})
	return n, mapUowError(err)
}

func (s *uowStore) CountIssueComments(ctx context.Context, issueID string) (int64, error) {
	u, err := s.provider.NewUOW(ctx)
	if err != nil {
		return 0, err
	}
	defer u.Close(ctx)
	n, err := u.CommentUseCase().CountCommentsForIssue(ctx, issueID)
	return n, mapUowError(err)
}

// ---- close-path reads (blocker check + molecule ancestry walk) ----
//
// `bd close` (store path) runs a pre-close blocker check (IsBlocked) and an
// unconditional parent-molecule auto-close probe (findParentMolecules ->
// GetDependencyRecordsForIssues, cmd/bd/mol_current.go:413). Both are DIRECT
// maps onto DependencyUseCase.

func (s *uowStore) IsBlocked(ctx context.Context, issueID string) (bool, []string, error) {
	u, err := s.provider.NewUOW(ctx)
	if err != nil {
		return false, nil, err
	}
	defer u.Close(ctx)
	blocked, blockers, err := u.DependencyUseCase().IsBlocked(ctx, issueID)
	return blocked, blockers, mapUowError(err)
}

func (s *uowStore) GetDependencyRecordsForIssues(ctx context.Context, issueIDs []string) (map[string][]*types.Dependency, error) {
	u, err := s.provider.NewUOW(ctx)
	if err != nil {
		return nil, err
	}
	defer u.Close(ctx)
	out, err := u.DependencyUseCase().GetForIssueIDs(ctx, issueIDs)
	return out, mapUowError(err)
}

// ---- config-metadata reads (ConfigMetadataStore) ----
//
// These are NOT part of the original 5-8 core issue methods, but the core read
// commands (list/create/show/ready) transitively require them: the CLI's list
// filter loader calls GetCustomStatusesDetailed/GetCustomTypes/GetInfraTypes on
// the store before it ever calls SearchIssues (cmd/bd/list_filter.go). So a
// working vertical slice for those commands must implement them too. They are
// all DIRECT 1:1 maps onto domain.ConfigUseCase — with two signature snags the
// adapter absorbs: the store's GetInfraTypes/IsInfraTypeCtx drop the error the
// use-case returns.

func (s *uowStore) GetCustomStatusesDetailed(ctx context.Context) ([]types.CustomStatus, error) {
	u, err := s.provider.NewUOW(ctx)
	if err != nil {
		return nil, err
	}
	defer u.Close(ctx)
	out, err := u.ConfigUseCase().GetCustomStatuses(ctx)
	return out, mapUowError(err)
}

func (s *uowStore) GetCustomTypes(ctx context.Context) ([]string, error) {
	u, err := s.provider.NewUOW(ctx)
	if err != nil {
		return nil, err
	}
	defer u.Close(ctx)
	out, err := u.ConfigUseCase().GetCustomTypes(ctx)
	return out, mapUowError(err)
}

// GetInfraTypes drops the error to satisfy the store signature — a spike
// simplification. A real adapter needs a signature-compatible surface here (the
// store contract has no error channel), which is a documented §4 friction point.
func (s *uowStore) GetInfraTypes(ctx context.Context) map[string]bool {
	u, err := s.provider.NewUOW(ctx)
	if err != nil {
		return nil
	}
	defer u.Close(ctx)
	out, err := u.ConfigUseCase().GetInfraTypes(ctx)
	if err != nil {
		return nil
	}
	return out
}

// IsInfraTypeCtx is the other no-error-channel store method (same snag as
// GetInfraTypes: the use-case returns (bool, error), the store contract returns
// bare bool). It MUST be a real override, not left to the generated shell: the
// shell's zero-value stub silently answers false, and this is reachable under
// BD_SPIKE_UOWSTORE=1 from cmd/bd/wisp.go (store.IsInfraTypeCtx gates infra-type
// wisp handling at :637/:682/:759). A silent false there is exactly the
// silent-divergence class this spike exists to surface, so we swallow the error
// to false — loud typed errors are impossible on this signature, but a real
// override at least routes to the use-case instead of the stub.
func (s *uowStore) IsInfraTypeCtx(ctx context.Context, t types.IssueType) bool {
	u, err := s.provider.NewUOW(ctx)
	if err != nil {
		return false
	}
	defer u.Close(ctx)
	isInfra, err := u.ConfigUseCase().IsInfraTypeCtx(ctx, t)
	if err != nil {
		return false
	}
	return isInfra
}

// GetConfig / GetAllConfig back the CLI's repo auto-routing preflight
// (cmd/bd/routing_read.go), which every read command runs before touching
// issues. Both are DIRECT maps onto domain.ConfigUseCase.
func (s *uowStore) GetConfig(ctx context.Context, key string) (string, error) {
	u, err := s.provider.NewUOW(ctx)
	if err != nil {
		return "", err
	}
	defer u.Close(ctx)
	out, err := u.ConfigUseCase().GetConfig(ctx, key)
	return out, mapUowError(err)
}

func (s *uowStore) GetAllConfig(ctx context.Context) (map[string]string, error) {
	u, err := s.provider.NewUOW(ctx)
	if err != nil {
		return nil, err
	}
	defer u.Close(ctx)
	out, err := u.ConfigUseCase().GetAllConfig(ctx)
	return out, mapUowError(err)
}

// ---- PreRun-surface reads (not command handlers, but on every write path) ----
//
// These are NOT reached by any of the five headline commands' RunE, but by the
// PersistentPreRunE helpers that run BEFORE it: validateWorkspaceIdentity calls
// GetMetadata (main.go:1441) for every write command, and maybeAutoImportJSONL
// calls GetStatistics (auto_import_upgrade.go) on any workspace with a non-empty
// issues.jsonl. Without them the spike store nil-panics before RunE on real
// workspaces — the transitive census in §4 must cover PreRun, not just handlers.
// Both are DIRECT 1:1 use-case maps.

func (s *uowStore) GetMetadata(ctx context.Context, key string) (string, error) {
	u, err := s.provider.NewUOW(ctx)
	if err != nil {
		return "", err
	}
	defer u.Close(ctx)
	out, err := u.ConfigUseCase().GetMetadata(ctx, key)
	return out, mapUowError(err)
}

func (s *uowStore) GetStatistics(ctx context.Context) (*types.Statistics, error) {
	u, err := s.provider.NewUOW(ctx)
	if err != nil {
		return nil, err
	}
	defer u.Close(ctx)
	out, err := u.IssueUseCase().GetStatistics(ctx)
	return out, mapUowError(err)
}

// ---- lifecycle ----

// Close releases the provider's pooled connections (§4.5 mapping). It is never
// reached on the CLI spike path — PostRun's store.Close() at main.go sits in the
// else of `if proxiedServerMode`, which stays true under the flag — but the
// direct-handle tests use it to release pooled connections deterministically.
func (s *uowStore) Close() error {
	return s.provider.Close(context.Background())
}

// ---- helpers (package-level so the tx view and the store methods share ONE
// error-mapping/resolution implementation) ----

// getIssueInUOW is the shared body of GetIssue: probe the issues table, fall
// back to wisps, and translate the uow path's wrapped sql.ErrNoRows to the
// store contract's storage.ErrNotFound. Used by (*uowStore).GetIssue AND
// (*uowTransaction).GetIssue so errors.Is(err, storage.ErrNotFound) behaves
// identically inside and outside a transaction.
func getIssueInUOW(ctx context.Context, u uow.UnitOfWork, id string) (*types.Issue, error) {
	issue, err := u.IssueUseCase().GetIssue(ctx, id)
	if err == nil {
		// Hydrate labels from the issues-side label table, matching embedded's
		// issueops.GetIssueInTx (it always populates issue.Labels). The domain
		// use-case GetIssue returns only the row, so without this the close/show
		// return objects carry labels=null even though the labels persist —
		// #4547 F-5. GetLabels routes to `labels` for a regular issue.
		labels, lerr := u.LabelUseCase().GetLabels(ctx, id)
		if lerr != nil {
			return nil, lerr
		}
		issue.Labels = labels
		return issue, nil
	}
	if !isNotFound(err) {
		return nil, err
	}

	wisp, werr := u.IssueUseCase().GetWisp(ctx, id)
	if werr == nil {
		// Wisp-side hydration reads wisp_labels, mirroring GetIssueInTx's
		// issues→wisps table fallback (labels→wisp_labels).
		labels, lerr := u.LabelUseCase().GetWispLabels(ctx, id)
		if lerr != nil {
			return nil, lerr
		}
		wisp.Labels = labels
		return wisp, nil
	}
	if isNotFound(werr) {
		return nil, fmt.Errorf("%w: issue %s", storage.ErrNotFound, id)
	}
	return nil, werr
}

// isWispInUOW reports whether id lives in the wisps table, given an open UOW. It
// distinguishes wisp from regular by probing GetIssue first (matching the
// proxied command's proxiedResolveIssueOrWisp order).
func isWispInUOW(ctx context.Context, u uow.UnitOfWork, id string) (bool, error) {
	if _, err := u.IssueUseCase().GetIssue(ctx, id); err == nil {
		return false, nil
	} else if !isNotFound(err) {
		return false, err
	}
	if _, err := u.IssueUseCase().GetWisp(ctx, id); err == nil {
		return true, nil
	} else if !isNotFound(err) {
		return false, err
	}
	// Not found in either table; let the close use-case surface the canonical
	// not-found error rather than guessing a table here.
	return false, nil
}

// closeIssueInUOW is the shared body of CloseIssue's write closure: probe
// issue-vs-wisp, then route to the matching close use-case with
// domain.CloseIssueParams. Used by (*uowStore).CloseIssue AND
// (*uowTransaction).CloseIssue.
func closeIssueInUOW(ctx context.Context, u uow.UnitOfWork, id, reason, actor, session string) error {
	params := domain.CloseIssueParams{Reason: reason, Session: session}
	isWisp, err := isWispInUOW(ctx, u, id)
	if err != nil {
		return err
	}
	if isWisp {
		_, err = u.IssueUseCase().CloseWisp(ctx, id, params, actor)
	} else {
		_, err = u.IssueUseCase().CloseIssue(ctx, id, params, actor)
	}
	return err
}

// prepareForCreate reproduces the pre-write state EmbeddedDoltStore.CreateIssue
// computes before it opens its write tx, so the spike and the default embedded
// store accept and reject exactly the same `bd create` inputs:
//
//   - Infra-type ephemeral flip. EmbeddedDoltStore.CreateIssue marks every infra
//     type ephemeral UNCONDITIONALLY (create_issue.go:19-21 — note it has no
//     `!issue.NoHistory` guard; that guard lives only on the legacy DoltStore /
//     batch paths). Mirroring that unconditional flip is load-bearing: an infra
//     type created with --no-history must land in the ephemeral+no_history state
//     the validator then declares impossible, so the spike rejects it just like
//     embedded. Guarding the flip here would instead let that combo through as a
//     silent no_history wisp — the opposite of parity.
//   - Issue validation. Embedded validates via issueops.PrepareIssueForInsert ->
//     Issue.ValidateWithCustom (create.go:433); the domain create use-case never
//     does, so without this the spike silently accepts custom-only types like
//     agent/role (types.go custom-only set) and the ephemeral+no_history combo
//     that embedded refuses with exit 1 (#4547 Slice-4 red-team). Custom statuses
//     and types are resolved through the same ConfigUseCase the embedded path
//     reads (custom_types table -> types.custom config -> YAML union), so a
//     genuinely configured custom type still validates on both plumbings.
//
// Runs in one read-only UOW so the flag and the custom status/type sets are
// resolved before the write tx opens (RunInTxMsg may replay fn, so this must stay
// idempotent and pre-computed). The validation error is wrapped exactly as
// PrepareIssueForInsert wraps it so the CLI-visible message is byte-identical.
func (s *uowStore) prepareForCreate(ctx context.Context, issue *types.Issue) error {
	u, err := s.provider.NewUOW(ctx)
	if err != nil {
		return err
	}
	defer u.Close(ctx)

	isInfra, err := u.ConfigUseCase().IsInfraTypeCtx(ctx, issue.IssueType)
	if err != nil {
		return fmt.Errorf("infra-type routing: %w", err)
	}
	if isInfra {
		issue.Ephemeral = true
	}

	customStatuses, err := u.ConfigUseCase().GetCustomStatuses(ctx)
	if err != nil {
		return mapUowError(err)
	}
	customTypes, err := u.ConfigUseCase().GetCustomTypes(ctx)
	if err != nil {
		return mapUowError(err)
	}
	statusNames := make([]string, 0, len(customStatuses))
	for _, st := range customStatuses {
		statusNames = append(statusNames, st.Name)
	}
	if err := issue.ValidateWithCustom(statusNames, customTypes); err != nil {
		return fmt.Errorf("validation failed for issue %s: %w", issue.ID, err)
	}
	return nil
}

// isNotFound covers both the storage-package sentinel and the raw sql.ErrNoRows
// that the domain repositories wrap, so the adapter can translate the uow
// path's not-found convention to the store contract's storage.ErrNotFound.
func isNotFound(err error) bool {
	return errors.Is(err, storage.ErrNotFound) || errors.Is(err, sql.ErrNoRows)
}
